# Generated by Django 6.0.2 on 2026-02-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('vehicle_type', models.CharField(choices=[('tout-terrain', 'Véhicule Tout-Terrain'), ('poids-lourd', 'Poids Lourd / Camion'), ('engin-btp', 'Engin BTP / Chantier'), ('autre', 'Autre')], max_length=50, verbose_name='Type de véhicule')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('in_progress', 'En cours de traitement'), ('replied', 'Répondu'), ('closed', 'Clôturé')], default='new', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
